apiVersion: v2
name: greetings
description: A Helm chart for deploying a demo Flask App to Amazon EC2

# A chart can be either an 'application' or a 'library' chart.
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
version: 0.1.0

# This is the version number of the application being deployed. This version number should be
appVersion: "1.16.0"
maintainers:
  - name: Melvin Kimathi
    url: https://github.com/MelvinKim
