apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
    team:  {{ .Values.app.team }}
spec:
  replicas: {{ .Values.app.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        team: {{ .Values.app.team }}
    spec:
      containers:
        - name: {{ .Release.Name }}
          image: {{ .Values.app.container.image }}
          imagePullPolicy: {{ .Values.app.container.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.app.container.containerPort }}
          resources:
            limits:
              memory: {{ .Values.app.container.resources.memoryLimit }}
              cpu: {{ .Values.app.container.resources.cpuLimit }}
